location ^~ /build/ {
    access_log off;
    expires 1y;
    add_header Cache-Control "public, max-age=31536000, immutable";
    try_files $uri =404;
}

location ^~ /storage/ {
    expires 30d;
    add_header Cache-Control "public, max-age=2592000";
    try_files $uri =404;
}

location ~* ^/(css|js|fonts)/ {
    access_log off;
    expires 7d;
    add_header Cache-Control "public, max-age=604800";
    try_files $uri =404;
}
