services:
  nginx:
    ports:
      - "80:80"
    volumes:
      - ./certbot/www:/var/www/certbot:ro
      - ./docker/nginx/snippets:/etc/nginx/snippets:ro
    restart: unless-stopped

  app:
    restart: unless-stopped

  postgres:
    restart: unless-stopped

  redis:
    restart: unless-stopped
